name = "identify"
license = "MIT"
licenselink = "https://github.com/posquit0/hugo-awesome-identity/blob/master/LICENSE"
description = "Awesome Identity is a single-page Hugo theme to introduce yourself."
homepage = "https://github.com/posquit0/hugo-awesome-identity"
tags = [
  "aboutme", "awesome", "identity", "minimal",  "minimalist", "simple", "clean",
  "responsive", "mobile", "one-page", "onepage", "light", "landing page", "starter"
]
features = ["favicon"]
min_version = "0.53"

[author]
  name = "Byungjin Park"
  homepage = "https://www.posquit0.com"
